numero1 = int(input("Insira o primeiro número inteiro: "))
numero2 = int(input("Insira o segundo número inteiro: "))
soma = (numero1 + numero2)
produto = (numero1 * numero2)
print(f"A soma dos numeros: { soma }" f" O produto dos numeros: { produto }")